server:
  port: 8081
spring:
  application:
    name: "Ping"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        ping-out-0:
          destination: ping.out
          producer:
            partition-count: 3
            partition-key-expression: headers.name
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: true
        bindings:
          ping-out-0:
            consumer:
              configuration:
                "auto.offset.reset": latest